name: samurai-cras-2021
channels:
  - conda-forge
dependencies:
  - cxx-compiler=1.2.0
  - cmake=3.19.5
  - xtensor=0.23.10
  - xtensor-io=0.12.1
  - fmt=7.1.3
  - pugixml=1.11.4
  - cxxopts=2.2.1
  - python=3.9.7
  - matplotlib=3.5.0
  - seaborn=0.11.2
  - pip:
      - h5py
      - jupyterlab_latex
