#!/bin/bash

set -ex

git clone https://github.com/hpc-maths/samurai.git

echo $NB_PYTHON_PREFIX


pushd samurai
git checkout -b cras_note 3062795
mkdir build
pushd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$NB_PYTHON_PREFIX
make install
popd
popd

rm -r samurai

mkdir build
pushd build

cmake .. -DCMAKE_BUILD_TYPE=Release
make

mv ./src/D1Q3_case ./src/D2Q9_case ..
popd

rm -r build
mkdir D1Q3_jump_compte_rendus
mkdir D2Q9_jump_compte_rendus